/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_videotest_VideoItem */

#ifndef _Included_com_videotest_VideoItem
#define _Included_com_videotest_VideoItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_videotest_VideoItem
 * Method:    getLinkPreview
 * Signature: (Ljava/lang/String;IILandroid/graphics/Bitmap;)I
 */
JNIEXPORT jint JNICALL Java_com_videotest_VideoItem_getLinkPreview
  (JNIEnv *, jobject, jstring, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
